### ISSUE TITLE
Initialize project

### ISSUE THREAD

**Issue by yuwtennis** [yuwtennis/velocity#1]
# Tasks

- [ ] Create Makefile target for creating schema on bigquery
- [ ] Create and deploy for google app script
- [ ] Run google app script
- [ ] Connect to BigQuery using Data Studio 360
- [ ] Gen report on Data Studio 360
